### ISSUE TITLE
Create initial VagrantFile and Flask file

### ISSUE THREAD

**Issue by sadam0930** [nyu-delta-squad-s17/recommendation-service#1]

**Comment by ceciliazhang12** [comment]
Hi @u932b Can you get your vagrant environment run? 
I tried `vagrant up` but it sends me an error like "The VirtualBox VM was created with a user that doesn't match the current user running Vagrant." Any advice?

**Comment by 0x932b** [comment]
Hey @ceciliazhang12 it seemed like .vagrant should be put into .gitignore
alternative you can edit .vagrant/machines/default/virtualbox/creator_uid to the uid the error log is addressing (probably 501)

http://stackoverflow.com/questions/31644222/vagrant-not-starting-up-user-that-created-vm-doesnt-match-current-user

**Comment by 0x932b** [comment]
@sadam0930 do we open a new issue for this?

**Comment by sadam0930** [comment]
I created a fix, but I guess I should create a new pull request

**Comment by sadam0930** [comment]
This is fixed in #10
