### ISSUE TITLE
Create swagger docs

### ISSUE THREAD

**Issue by sadam0930** [nyu-delta-squad-s17/recommendation-service#113]
**As a** ...  
**I need** ...  
**So that** ...  

**Assumptions:** 
* ...

**Acceptance Criteria:**
```
Given ...
When ...
Then ...
```

**Comment by 0x932b** [comment]
that's divide this ?

**Comment by sadam0930** [comment]
In theory one person can do this fairly quickly (with some breaks to break up the monotony), but we can break it up per endpoint. I doubt we need to have a meeting to do that if someone just wants to create the stories.

**Comment by sadam0930** [comment]
We will break this into multiple stories per API
