### ISSUE TITLE
Perform some Action on the Resource

### ISSUE THREAD

**Issue by sadam0930** [nyu-delta-squad-s17/recommendation-service#29]
**As a** seller
**I need** to prioritize recommended products that users click on
**So that** I show other buyers this product first

**Assumptions:** 
* Low priority --> High Priority
* 5 ---> 1

**Acceptance Criteria:**
```
Given a PUT /recommendation/{id}/clicked
When this request is received
Then I increase the priority of that product
```

**Comment by 0x932b** [comment]
http://0.0.0.0:5000/recommendations/click_demo is a demonstration page of the api at work
