### ISSUE TITLE
create get List API

### ISSUE THREAD

**Issue by sadam0930** [nyu-delta-squad-s17/recommendation-service#4]
As a user
I need to get a list of recommendations for a related product
So that I buy more things

Acceptance Criteria:
getRecommendations returns json with a list of products

**Comment by 0x932b** [comment]
so I was thinking we should seperate like get and list:
somethin like GET /recomm/

for List i was thinking: 
{
'A':[1,2,3,4,5],
'B':[2,3,4,]
}
and for GET a was thinking in terms of getting specifics for one product:
which is probably undet GET /recomm/prouduct_uid:
{
'1': {'weight':'', 'date':, 'blah'},
'2':{}
}
