### ISSUE TITLE
POST/PUT API handles errors gracefully

### ISSUE THREAD

**Issue by jiweix** [nyu-delta-squad-s17/recommendation-service#47]
**As a** developer 
**I need** handle invalid data
**So that** exceptions are handled and api response to invalid data is consistent for all api

**Assumptions:** 
* function validate(data) should be called to make sure incoming request with JSON

**Acceptance Criteria:**
```
Given JSON with invalid data type (None instead of null, string instead of number)
When the PUT/POST is called with invalid data
Then response should be HTTP_400_BAD_REQUEST instead of 500 Internal Server Error. 
```

**Comment by sadam0930** [comment]
@jiweix does this duplicate #17 ?

**Comment by jiweix** [comment]
They are similar problems. I think #17 is related to business rules. Such as is the type valid, is the product valid. This issue focus on handling errors that caused by "bad" input. We should handle the exceptions and not throw the error to the user.
