### ISSUE TITLE
create update API

### ISSUE THREAD

**Issue by sadam0930** [nyu-delta-squad-s17/recommendation-service#6]
As a seller
I need to update my product in the inventory with related items
So that the correct related items are shown to customers

Acceptance Criteria:
updateRecommendations updates the given item and related items

Assumptions:
* Replace the current list of recommendations with a brand new list. (This will be very similar to the create API)
* Update the record in the database

**Comment by 0x932b** [comment]
As discussed, the update API only updates type and priority. For parent or the related product and IDs, it's a new recommendation
