### ISSUE TITLE
create GET unit tests for queries (both pass and fail)

### ISSUE THREAD

**Issue by sadam0930** [nyu-delta-squad-s17/recommendation-service#71]
**As a** developer
**I need** unit tests
**So that** I know I didn't break anything when I merge to master

**Assumptions:** 
* **Decide between PyUnit syntax or Expect syntax**

**Acceptance Criteria:**
```
Given a GET /recommendations request
When the test is executed
Then I see green that the tests passed
```

**Comment by 0x932b** [comment]
Unitest for Issue #28
