### ISSUE TITLE
Create GET unit test (Pass and Fail)

### ISSUE THREAD

**Issue by rohithreddy1** [nyu-delta-squad-s17/recommendation-service#72]
**As a developer**
I need unit tests
So that I know I didn't break anything when I merge to master

**Assumptions:**

**Decide between PyUnit syntax or Expect syntax**
Acceptance Criteria:

Given a GET /recommendations request
When the test is executed
Then I see green that the tests passed

**Comment by sadam0930** [comment]
This is to cover a normal read request for one item or a list.

**Comment by sadam0930** [comment]
Fixed with #68
